//! Git-compatible metadata generation for dumb/static transports.

use std::collections::BTreeSet;
use std::path::Path;

use crate::{Error, PackIndex, Repository, Result, ShowRefOptions};

/// Publication and resource policy for server-info files.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ServerInfoOptions {
    /// Rewrite files even when generated bytes are unchanged.
    pub force: bool,
    /// Generate and compare without writing or removing anything.
    pub dry_run: bool,
    pub max_references: usize,
    pub max_reference_depth: usize,
    pub max_tag_depth: usize,
    pub max_object_size: usize,
    pub max_packs: usize,
    pub max_pack_index_size: usize,
}

impl Default for ServerInfoOptions {
    fn default() -> Self {
        Self {
            force: false,
            dry_run: false,
            max_references: 1_000_000,
            max_reference_depth: 4096,
            max_tag_depth: 64,
            max_object_size: 1024 * 1024 * 1024,
            max_packs: 1_000_000,
            max_pack_index_size: 1024 * 1024 * 1024,
        }
    }
}

/// Generated inventory sizes and whether each publication was necessary.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ServerInfoReport {
    pub references: usize,
    pub peeled_tags: usize,
    pub packs: usize,
    pub refs_changed: bool,
    pub packs_changed: bool,
    pub removed_rev_cache: bool,
}

impl Repository {
    /// Generate `info/refs` and `objects/info/packs` for dumb transports.
    ///
    /// Each changed file is published through lock-and-rename. Existing pack
    /// order is retained when it describes only packs that still exist; newly
    /// discovered packs follow in bytewise filename order.
    ///
    /// # Errors
    /// Returns an error for malformed/broken refs or tags, invalid pack names or
    /// indexes, resource-limit violations, lock contention, or storage failures.
    pub fn update_server_info(&self, options: &ServerInfoOptions) -> Result<ServerInfoReport> {
        let refs = self.show_refs(&ShowRefOptions {
            dereference_tags: true,
            max_references: options.max_references,
            max_depth: options.max_reference_depth,
            max_tag_depth: options.max_tag_depth,
            max_object_size: options.max_object_size,
            ..ShowRefOptions::default()
        })?;
        let mut refs_data = Vec::new();
        let mut references = 0usize;
        let mut peeled_tags = 0usize;
        for entry in refs {
            refs_data.extend_from_slice(format!("{}\t{}\n", entry.id(), entry.name()).as_bytes());
            if entry.is_peeled() {
                peeled_tags += 1;
            } else {
                references += 1;
            }
        }

        let current_packs = self.server_pack_names(options)?;
        let old_pack_data = read_optional(self, "objects/info/packs")?;
        let ordered_packs = ordered_pack_names(old_pack_data.as_deref(), &current_packs);
        let mut packs_data = Vec::new();
        for name in &ordered_packs {
            packs_data.extend_from_slice(b"P ");
            packs_data.extend_from_slice(name.as_bytes());
            packs_data.push(b'\n');
        }
        packs_data.push(b'\n');

        let old_refs = read_optional(self, "info/refs")?;
        let refs_changed = options.force || old_refs.as_deref() != Some(refs_data.as_slice());
        let packs_changed =
            options.force || old_pack_data.as_deref() != Some(packs_data.as_slice());
        let rev_cache = self.git_path("info/rev-cache");
        let removed_rev_cache = self.filesystem().exists(&rev_cache)?;
        if !options.dry_run {
            if refs_changed {
                self.write_atomic(Path::new("info/refs"), &refs_data)?;
            }
            if packs_changed {
                self.write_atomic(Path::new("objects/info/packs"), &packs_data)?;
            }
            if removed_rev_cache {
                self.filesystem().remove_file(&rev_cache)?;
            }
        }
        Ok(ServerInfoReport {
            references,
            peeled_tags,
            packs: ordered_packs.len(),
            refs_changed,
            packs_changed,
            removed_rev_cache,
        })
    }

    fn server_pack_names(&self, options: &ServerInfoOptions) -> Result<BTreeSet<String>> {
        let directory = self.git_path("objects/pack");
        let children = match self.filesystem().read_dir(&directory) {
            Ok(children) => children,
            Err(Error::NotFound(_)) => return Ok(BTreeSet::new()),
            Err(error) => return Err(error),
        };
        let mut names = BTreeSet::new();
        for child in children {
            if child.extension().and_then(|value| value.to_str()) != Some("pack") {
                continue;
            }
            let name = child
                .to_str()
                .ok_or_else(|| Error::InvalidRepository("non-UTF-8 pack filename".into()))?;
            validate_pack_name(name)?;
            let index_path = directory.join(child.with_extension("idx"));
            let metadata = self.filesystem().metadata(&index_path)?;
            let declared = usize::try_from(metadata.len()).unwrap_or(usize::MAX);
            if declared > options.max_pack_index_size {
                return Err(Error::ObjectTooLarge {
                    declared: metadata.len(),
                    limit: options.max_pack_index_size,
                });
            }
            PackIndex::parse(&self.filesystem().read(&index_path)?)?;
            names.insert(name.to_owned());
            if names.len() > options.max_packs {
                return Err(Error::InvalidRepository(format!(
                    "server-info exceeds {} packs",
                    options.max_packs
                )));
            }
        }
        Ok(names)
    }
}

fn read_optional(repository: &Repository, path: &str) -> Result<Option<Vec<u8>>> {
    match repository.read_git_file(path) {
        Ok(data) => Ok(Some(data)),
        Err(Error::NotFound(_)) => Ok(None),
        Err(error) => Err(error),
    }
}

fn validate_pack_name(name: &str) -> Result<()> {
    let hash = name
        .strip_prefix("pack-")
        .and_then(|value| value.strip_suffix(".pack"))
        .ok_or_else(|| Error::InvalidRepository(format!("invalid pack filename `{name}`")))?;
    if hash.len() != 40 || !hash.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(Error::InvalidRepository(format!(
            "invalid pack filename `{name}`"
        )));
    }
    Ok(())
}

fn ordered_pack_names(old: Option<&[u8]>, current: &BTreeSet<String>) -> Vec<String> {
    let Some(old) = old.and_then(parse_old_pack_names) else {
        return current.iter().cloned().collect();
    };
    if old.iter().any(|name| !current.contains(name)) {
        return current.iter().cloned().collect();
    }
    let old_set = old.iter().cloned().collect::<BTreeSet<_>>();
    old.into_iter()
        .chain(current.difference(&old_set).cloned())
        .collect()
}

fn parse_old_pack_names(data: &[u8]) -> Option<Vec<String>> {
    let mut names = Vec::new();
    let mut seen = BTreeSet::new();
    for line in data
        .split(|byte| *byte == b'\n')
        .filter(|line| !line.is_empty())
    {
        let name = line.strip_prefix(b"P ")?;
        let name = std::str::from_utf8(name).ok()?.to_owned();
        validate_pack_name(&name).ok()?;
        if !seen.insert(name.clone()) {
            return None;
        }
        names.push(name);
    }
    Some(names)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        FileSystem, InitOptions, MemoryFileSystem, ObjectKind, PackOptions, PreviousValue,
        ReferenceName, Signature, TagBuilder,
    };

    #[test]
    fn publishes_refs_peeled_tags_and_packs_then_avoids_unchanged_writes() {
        let fs = MemoryFileSystem::new();
        let repository = Repository::init(fs.clone(), "repo", &InitOptions::default()).unwrap();
        let blob = repository.write_object(ObjectKind::Blob, b"value").unwrap();
        repository
            .update_reference(
                &ReferenceName::branch("main").unwrap(),
                blob,
                PreviousValue::Any,
            )
            .unwrap();
        let tag = TagBuilder::new(
            blob,
            ObjectKind::Blob,
            b"v1",
            Signature::new("Tagger", "tagger@example.com", 1, 0).unwrap(),
        )
        .unwrap()
        .build();
        let (_, tag_id) = repository
            .create_annotated_tag("v1", &tag, false, 4096)
            .unwrap();
        let written = repository
            .write_pack(&[blob, tag_id], &PackOptions::default())
            .unwrap();
        fs.write(Path::new("repo/.git/info/rev-cache"), b"stale")
            .unwrap();

        let report = repository
            .update_server_info(&ServerInfoOptions::default())
            .unwrap();
        assert_eq!(report.references, 2);
        assert_eq!(report.peeled_tags, 1);
        assert_eq!(report.packs, 1);
        assert!(report.refs_changed && report.packs_changed && report.removed_rev_cache);
        assert_eq!(
            fs.read(Path::new("repo/.git/info/refs")).unwrap(),
            format!("{blob}\trefs/heads/main\n{tag_id}\trefs/tags/v1\n{blob}\trefs/tags/v1^{{}}\n")
                .as_bytes()
        );
        let pack_name = written.pack_path.file_name().unwrap().to_str().unwrap();
        assert_eq!(
            fs.read(Path::new("repo/.git/objects/info/packs")).unwrap(),
            format!("P {pack_name}\n\n").as_bytes()
        );
        assert!(matches!(
            fs.read(Path::new("repo/.git/info/rev-cache")),
            Err(Error::NotFound(_))
        ));

        let unchanged = repository
            .update_server_info(&ServerInfoOptions::default())
            .unwrap();
        assert!(!unchanged.refs_changed);
        assert!(!unchanged.packs_changed);
    }

    #[test]
    fn dry_run_previews_without_mutation_and_force_republishes() {
        let fs = MemoryFileSystem::new();
        let repository = Repository::init(fs.clone(), "repo", &InitOptions::default()).unwrap();
        let first = repository.write_object(ObjectKind::Blob, b"one").unwrap();
        repository
            .update_reference(
                &ReferenceName::branch("main").unwrap(),
                first,
                PreviousValue::Any,
            )
            .unwrap();
        repository
            .update_server_info(&ServerInfoOptions::default())
            .unwrap();
        let before = fs.read(Path::new("repo/.git/info/refs")).unwrap();
        let second = repository.write_object(ObjectKind::Blob, b"two").unwrap();
        repository
            .update_reference(
                &ReferenceName::branch("other").unwrap(),
                second,
                PreviousValue::Any,
            )
            .unwrap();
        let preview = repository
            .update_server_info(&ServerInfoOptions {
                dry_run: true,
                ..ServerInfoOptions::default()
            })
            .unwrap();
        assert!(preview.refs_changed);
        assert_eq!(fs.read(Path::new("repo/.git/info/refs")).unwrap(), before);
        let forced = repository
            .update_server_info(&ServerInfoOptions {
                force: true,
                ..ServerInfoOptions::default()
            })
            .unwrap();
        assert!(forced.refs_changed && forced.packs_changed);
    }

    #[test]
    fn retains_valid_old_pack_order_and_rejects_missing_index() {
        let fs = MemoryFileSystem::new();
        let repository = Repository::init(fs.clone(), "repo", &InitOptions::default()).unwrap();
        let first = repository.write_object(ObjectKind::Blob, b"one").unwrap();
        let second = repository.write_object(ObjectKind::Blob, b"two").unwrap();
        let first = repository
            .write_pack(&[first], &PackOptions::default())
            .unwrap();
        let second = repository
            .write_pack(&[second], &PackOptions::default())
            .unwrap();
        let first_name = first.pack_path.file_name().unwrap().to_str().unwrap();
        let second_name = second.pack_path.file_name().unwrap().to_str().unwrap();
        fs.write(
            Path::new("repo/.git/objects/info/packs"),
            format!("P {second_name}\nP {first_name}\n\n").as_bytes(),
        )
        .unwrap();
        let report = repository
            .update_server_info(&ServerInfoOptions::default())
            .unwrap();
        assert!(!report.packs_changed);

        fs.write(
            Path::new("repo/.git/objects/pack/pack-1111111111111111111111111111111111111111.pack"),
            b"broken",
        )
        .unwrap();
        assert!(
            repository
                .update_server_info(&ServerInfoOptions::default())
                .is_err()
        );
    }
}
